apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-metrics-collector
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "nodes/proxy", "pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"] # Cho phép scrape trực tiếp endpoint metric hệ thống
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-global-monitoring-binding
subjects:
- kind: ServiceAccount
  name: prometheus-sa
  namespace: monitoring # Khai báo rõ ràng Namespace của SA
roleRef:
  kind: ClusterRole
  name: prometheus-metrics-collector
  apiGroup: rbac.authorization.k8s.io